name: f_bottom_nav_nested_route_demo
description: A new Flutter project to demonstrate bottom navigation with nested routing

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_route: ^3.2.4
  salomon_bottom_bar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.7

flutter:
  uses-material-design: true